algoritmo "Fatorial"
// Função :
// Autor :
// Data : 30/08/2022
// Seção de Declarações 
var
contador,numero,resultado:inteiro
inicio
escreva("Digite um número:")
leia(numero)

resultado <- 1
se (numero = 0) entao
  escreval("Resultado => ",resultado)
  senao
    para contador de 1 ate numero faca
      resultado <- resultado * contador
   fimpara
fimse
escreval("Resultado => ",resultado)
// Seção de Comandos 
fimalgoritmo
