algoritmo "Fibonacci"
var
anterior: inteiro
posterior: inteiro
resultado: inteiro
quantidade: inteiro
contador: inteiro

inicio
// Seção de Comandos

Escreval("Digite a quantidade que deseja para sua sequencia Fibonacci")
leia(quantidade)

posterior <- 1

escreval(" 1")

para contador de 1 ate quantidade faca
resultado <- anterior + posterior
escreval(resultado)

anterior <- posterior
posterior <- resultado
resultado <- contador
fimpara
fimalgoritmo
