algoritmo "Competiçao_Volei"
// Fun??o :informe se ele pode ou nao competir no volei
// Autor :Bianca Gomes Da Silva
// Data :02/08/2022


var
idade: inteiro
altura: real
inicio

escreval("Qual sua idade?")
leia(idade)
escreval("Qual sua altura?")
leia(altura)

 se (altura < 1.75)entao
     escreval("Voce nao pode participar")

 senao entao
     escreval("Voce pode participar")

 fimse
fimalgoritmo
