algoritmo "ParOUÍmpar"
// Função :Descobrir se o número é par ou ímpar
// Autor :Bianca Gomes Da Silva
// Data :02/08/2022
// Seção de Declarações
var
num:inteiro
inicio
escreval("digite um numero: ")
leia(num)
se num mod 2 = 0 entao
           escreva("o número ", num, " é par!")
       senao
           escreva("o número ", num, " é ímpar!")
       fimse
// Seção de Comandos
fimalgoritmo
