algoritmo "CalculaMedia"
// Função :Calcular a media de 2 notas
// Autor :Bianca
// Data : 26/04/2022
// Seção de Declarações 
var
p1,p2,media:real
inicio
// DADOS DE ENTRADA
escreval("Entre com um valor para p1: ")
leia(p1)
escreval("Entre com um valor para p2: ")
leia(p2)
//FIM DOS DADOS DE ENTRADA
//PROCESSAMENTO
media <- (p1+p2)/2
//FIM PEOCESSAMENTO
//DADOS DE SAIDA
escreval("A média do aluno é: ",media)
//FIM DOS DADOS DE SAIDA


fimalgoritmo
