Algoritmo "vetor_01"
// Autor(a)    :Bianca Gomes da Silva
// Data atual  : 01/11/2022
Var

num: vetor[0..9] de inteiro
contador, soma: inteiro

Inicio
soma<-0
contador<-0
para contador de 0 ate 9 faca
     escreval("Digite um número")
     leia(num[contador])
     soma<-(num[contador])+soma
     contador<-contador+1
fimpara
escreval("A soma dos números equivale: ", soma)


Fimalgoritmo
