Algoritmo "vetor_02"
// Autor(a)    :Bianca Gomes da Silva
// Data atual  : 01/11/2022
Var

num: vetor[0..14] de inteiro
contador: inteiro

Inicio
contador<-0

para contador de 0 ate 14 faca
     escreval("Digite um número")
     leia(num[contador])
fimpara

para contador de 0 ate 14 faca
     se (num[contador])>0 entao
     escreval("Os números digitados positivos são: ", (num[contador]))
fimse
fimpara

Fimalgoritmo
