algoritmo "Calcularvt"
// Função :Calcular o valor total
// Autor :Bianca
// Data : 26/04/2022
// Seção de Declarações 
var
QTDE,VALOR,VT:real
inicio
// DADOS DE ENTRADA
escreval("Quantidade das peças é: ")
leia(QTDE)
escreval("Valor das peças é: ")
leia(VALOR)
//FIM DOS DADOS DE ENTRADA
//PROCESSAMENTO
VT <- QTDE*VALOR
//FIM PEOCESSAMENTO
//DADOS DE SAIDA
escreval("O valo total das peças é: ",VT)
//FIM DOS DADOS DE SAIDA


fimalgoritmo
